#Configuration file for the weather-server
# Rename this file into config.yaml and fill up your values
---
domain: api.openweathermap.org
key: ????????????????????????? #key-value
locations: 
- latitude: 0.0
  longitude: 0.0
- latitude: 10.0
  longitude: 10.0
- latitude: 20.0
  longitude: -20.0 
