#Configuration file for the weather-server
#Rename this file into config.yaml and fill up your values
---
serverPort  : 8080
domain: api.openweathermap.org
key: ????????????????????????  #key-value
timeDelay: 5                           # the period of automatic updates, seconds
marginErrorTime: 10                    # margin of error for time, seconds
locations: 
- location: London  
- location: Vladivostok  
- location: Vancouver 
- location: Saint John 
